receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  otlp:
    endpoint: http://host.containers.internal:4319
    tls:
      insecure: true
  otlphttp:
    endpoint: http://host.containers.internal:4320
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: http://host.containers.internal:9111/api/v1/write
    add_metric_suffixes: true
  loki:
    endpoint: http://host.containers.internal:3100/loki/api/v1/push

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
